In [ ]:
'''
Scenario: The executive team requires targeted subsets of operational employee data to review
critical internal metrics. Leverage conditional slicing, text comparison masks, and boolean
indexing operators (&, |) to partition the corporate DataFrame.
'''

## Question 1: Single Boolean Condition

In [ ]:
'''
The Head of IT needs to review the roster for his technical team. Write a Pandas statement to filter
and isolate all rows where the Department is exactly "IT/IS".
'''

In [1]:
import pandas as pd

In [9]:
df=pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [10]:
df['Department']

0         Production
1                     IT/IS
2         Production
3         Production
4         Production
               ...
577       Production
578       Production
579    Software Engineering
580       Production
581       Production
Name: Department, Length: 582, dtype: object

In [12]:
filtered=df[df['Department']=='IT/IS']
filtered.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
9,"Bacong, Alejandro",10250,0,2,1,1,3,3,0,50178,...,Peter Monroe,7.0,Indeed,Fully Meets,5.00,5,6,2/18/2019,0,16
12,"Barbossa, Hector",10012,0,2,1,1,3,4,1,92328,...,Simon Roup,4.0,Diversity Job Fair,Exceeds,4.28,4,5,2/25/2019,0,9
18,"Becker, Renee",10245,0,0,0,4,3,3,0,110000,...,Simon Roup,4.0,Google Search,Fully Meets,4.50,4,5,1/15/2015,0,8
20,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17

## Question 2: Multi-Condition Filtering using AND (&)

In [ ]:
'''
HR wants to find potential flight-risk or disengaged employees in production roles. 
Write a query to find all employees who are in the "Production" department AND
have an EmpSatisfaction score less than 3.
'''

In [13]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [14]:
filtered=df[(df['Department']=='Production') & (df['EmpSatisfaction']<3)]
filtered

Empty DataFrame
Columns: [Employee_Name, EmpID, MarriedID, MaritalStatusID, GenderID, EmpStatusID, DeptID, PerfScoreID, FromDiversityJobFairID, Salary, Termd, PositionID, Position, State, Zip, DOB, Gender, MaritalDesc, CitizenDesc, HispanicLatino, RaceDesc, DateofHire, DateofTermination, TermReason, EmploymentStatus, Department, ManagerName, ManagerID, RecruitmentSource, PerformanceScore, EngagementSurvey, EmpSatisfaction, SpecialProjectsCount, LastPerformanceReview_Date, DaysLateLast30, Absences]
Index: []

[0 rows x 36 columns]

## Question 3: Multi-Condition Filtering using OR (|)

In [ ]:
'''
The talent development team wants to reward recruitment channels. 
Filter for records where the employee was sourced via "Glassdoor" OR via "Employee Referral".
'''

In [15]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='object')

In [21]:
df['RecruitmentSource'].unique()

array(['LinkedIn', 'Indeed', 'Google Search', 'Employee Referral',
       'Diversity Job Fair', 'On-line Web application', 'CareerBuilder',
       'Website', 'Other'], dtype=object)

In [22]:
filtered=df[(df['RecruitmentSource']=='Glassdoor') | (df['RecruitmentSource']=='Employee Referral')]
filtered

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
7,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
16,"Beak, Kimberly",10023,1,1,0,2,5,4,0,70131,...,Kelley Spirea,18.0,Employee Referral,Exceeds,4.40,3,0,1/14/2019,0,16
26,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
35,"Beak, Kimberly",10023,1,1,0,2,5,4,0,70131,...,Kelley Spirea,18.0,Employee Referral,Exceeds,4.40,3,0,1/14/2019,0,16
52,"Burke, Joelle",10107,0,0,0,1,5,3,0,63763,...,Amy Dunn,11.0,Employee Referral,Fully Meets,4.51,4,0,2/21/2019,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
553,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
562,"Athwal, Sam",10062,0,4,1,1,5,3,0,500000,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
571,"Athwal, Sam",10062,0,4,1,1,5,3,0,500000,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19

## Question 4: Numeric Ranges and Column Slicing

In [ ]:
'''
Management is reviewing payroll and attendance anomalies. Filter for all employees who have a
Salary greater than 100,000 AND have logged more than 10 Absences. Display only their
Employee_Name, Position, and ManagerName.
'''

In [23]:
df['Salary']

0       62506
1      104437
2       64955
3       64991
4       50825
        ...
577     50825
578     57568
579     95660
580     59365
581     47837
Name: Salary, Length: 582, dtype: int64

In [24]:
df['Absences']

0       1
1      17
2       3
3      15
4       2
       ..
577     2
578    15
579    19
580    19
581     4
Name: Absences, Length: 582, dtype: int64

In [29]:
filtered=df[(df['Salary']>100000) & (df['Absences']>10)][['Employee_Name','Position','ManagerName']]
filtered

                Employee_Name                  Position       ManagerName
1    Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
20   Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
74             Corleone, Vito    Director of Operations        Janet King
115               Foss, Jason               IT Director   Jennifer Zamora
150           Houlihan, Debra         Director of Sales        Janet King
199            Martin, Sandra         Software Engineer   Alex Sweetwater
209             Monroe, Peter        IT Manager - Infra   Jennifer Zamora
231          Patronick, Lucas         Software Engineer   Alex Sweetwater
258          Roehrich, Bianca  Principal Data Architect        Simon Roup
259              Roper, Katie            Data Architect  Brian Champaigne
262                Roup,Simon           IT Manager - DB   Jennifer Zamora
327          Zamora, Jennifer                       CIO        Janet King
331  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
340  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
349  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
358  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
367  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
376  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
385  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
394  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
403  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
412  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
421  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
430  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
439  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
448  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
457  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
466  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
475  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
484  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
493  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
502  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
511  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
520  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
529  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
538  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
547  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
556  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
562               Athwal, Sam   Production Technician I     Ketsia Liebig
565  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup
570           Andreola, Colby         Software Engineer   Alex Sweetwater
571               Athwal, Sam   Production Technician I     Ketsia Liebig
574  Ait Sidi, Karthikeyan                      Sr. DBA        Simon Roup

## Question 5: Text Operations / ID Masking

In [ ]:
'''
Find all employees who work under the Manager "Kissy Sullivan" and have been late at least
once (DaysLateLast30 is greater than 0).
'''

In [30]:
df['ManagerName']

0       Michael Albert
1           Simon Roup
2       Kissy Sullivan
3         Elijiah Gray
4       Webster Butler
            ...
577     Webster Butler
578           Amy Dunn
579    Alex Sweetwater
580      Ketsia Liebig
581     Brannon Miller
Name: ManagerName, Length: 582, dtype: object

In [31]:
df['DaysLateLast30']

0      0
1      0
2      0
3      0
4      0
      ..
577    0
578    0
579    0
580    0
581    0
Name: DaysLateLast30, Length: 582, dtype: int64

In [32]:
filtered=df[(df['ManagerName']=='Kissy Sullivan') & (df['DaysLateLast30']>0)][['Employee_Name']]
filtered

     Employee_Name
72   Cole, Spencer
224   O'hare, Lynn