# Data Cleaning

In [1]:
'''
1. Handle missing / null values
    a. fill null values
        -> .fillna()
            continuous:
                - mean
                - median
                -> skewness -> .skew()
                 - 0-0.5 (fill mean value)
                 - <0 (negative skewness) or >0.5(positive skewness) (fill median value)
                 or
                -> calculate mean and median value of a column
                 - if both mean and median value are equal or almost equal, fill with mean
                 - else fill with median like for data with many outliers
            discrete / categorical:
                - mode
            continuous / discrete / categorical:
                - custom record
    b. drop null values
        -> .dropna()
        
2. Remove unwanted data
    -> remove whitespace
        - .strip(), .lstrip(), .rstrip()
    -> remove regular expressions (regex) if needed / remove unwanted texts
        - .replace()
        
3. Change Datatypes
    .astype()
    
4. Handle duplicate records
    -> find duplicate records
        -> .duplicated() / .duplicated(subset) for checking specific column
    -> remove duplicate records
        -> .drop_duplicates()
'''

'\n1. Handle missing / null values\n    a. fill null values\n        -> .fillna()\n            continuous:\n                - mean\n                - median\n                -> skewness -> .skew()\n                 - 0-0.5 (fill mean value)\n                 - <0 (negative skewness) or >0.5(positive skewness) (fill median value)\n                 or\n                -> calculate mean and median value of a column\n                 - if both mean and median value are equal or almost equal, fill with mean\n                 - else fill with median like for data with many outliers\n            discrete / categorical:\n                - mode\n            continuous / discrete / categorical:\n                - custom record\n    b. drop null values\n        -> .dropna()\n        \n2. Remove unwanted data\n    -> remove whitespace\n        - .strip(), .lstrip(), .rstrip()\n    -> remove regular expressions (regex) if needed / remove unwanted texts\n        - .replace()\n        \n3. Change Datatypes\n    .astype()\n    \n4. Handle duplicate records\n    -> find duplicate records\n        -> .duplicated() / .duplicated(subset) for checking specific column\n    -> remove duplicate records\n        -> .drop_duplicates()\n'

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [4]:
# check null values
df.isnull().sum() # shows column wise null values count

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [5]:
df.isnull().sum().sum() # sum every null values from all columns

78

## Drop Null Values

In [6]:
# -------------Row wise drop------------------------------------
# df.dropna() -> does temporary change and doesn't change the df
# df = df.dropna() -> one technique to change the df permanently
# df.dropna(inplace=True) another technique

In [7]:
'''
- dropna(axis=0/1, how='any'/'all', inplace= True/ False)

- axis -> 0 -> Row / 1-> Column
- how 
    -any -> data should have any one null value
    -all -> data must have all null values
- inplace
    -True -> permanent change to the copy of excel data i.e df
    -False -> temporary change to the copy of excel data i.e df
    (excel file doesn't change unless we replace it with the df)
- default 
    dropna() -> axis = 0, how = 'any', inplace = False
'''

"\n- dropna(axis=0/1, how='any'/'all', inplace= True/ False)\n\n- axis -> 0 -> Row / 1-> Column\n- how \n    -any -> data should have any one null value\n    -all -> data must have all null values\n- inplace\n    -True -> permanent change to the copy of excel data i.e df\n    -False -> temporary change to the copy of excel data i.e df\n    (excel file doesn't change unless we replace it with the df)\n- default \n    dropna() -> axis = 0, how = 'any', inplace = False\n"

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [9]:
df.dropna(axis=0,how='any',inplace=False)
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [10]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [11]:
# Drop any column
# df.drop(columns='EMAIL') for single column
df.drop(columns=['COMMISSION_PCT','PHONE_NUMBER']) # for multiple columns

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,6/17/2003,AD_PRES,24000,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,9/21/2005,AD_VP,17000,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,1/13/2001,AD_VP,17000,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,1/3/2006,IT_PROG,9000,102.0,60.0
4,104,Bruce,Ernst,BERNST,5/21/2007,IT_PROG,6000,103.0,60.0
...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,6/7/2002,AC_ACCOUNT,8300,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,6/7/2002,HR_REP,6500,101.0,40.0
108,204,Hermann,Baer,HBAER,6/7/2002,PR_REP,10000,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,6/7/2002,AC_MGR,12008,101.0,110.0
110,206,William,Gietz,WGIETZ,6/7/2002,AC_ACCOUNT,8300,205.0,110.0

In [12]:
# drop any row
df.drop(index=[0,1,2]) # for multiple rows

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [13]:
df.drop(index=4) # for single row

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

## Find duplicate records

In [14]:
duplicate_data= df[df.duplicated()]
duplicate_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [15]:
duplicate_data= df[df.duplicated(subset=['EMPLOYEE_ID'], keep=False)]
#if we remove keep=False then it will give the duplicated data once not with it's duplicates
duplicate_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

## Remove duplicates

In [16]:
df.drop_duplicates(subset='EMPLOYEE_ID', keep='last',inplace=True)
# keeps the last data and remove all duplicates above it

In [17]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

# Fill Null Values

In [18]:
df=pd.read_csv('Dataset/Employees.csv')

In [19]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

### Fill commission values

In [20]:
commission_mean=round(df['COMMISSION_PCT'].mean(),2)
commission_median=df['COMMISSION_PCT'].median()
commission_skew=df['COMMISSION_PCT'].skew()

In [21]:
print(commission_mean)
print(commission_median)
print(commission_skew)

0.22
0.2
0.09661736135041571

In [22]:
# df['COMMISSION_PCT'].fillna(commission_mean,inplace=True)
# avoid using this method

In [23]:
df.fillna({'COMMISSION_PCT':commission_mean},inplace=True)

In [24]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        1
DEPARTMENT_ID     1
dtype: int64

In [25]:
'''
df.fillna({'COMMISSION_PCT':0,},inplace=True)
to fill with custom value=0
'''

"\ndf.fillna({'COMMISSION_PCT':0,},inplace=True)\nto fill with custom value=0\n"

In [26]:
df['COMMISSION_PCT'].unique()

array([0.22, 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])

### Fill Manager and Department Values

In [27]:
# we should keep zero index since some columns can have multiple modes
# by keeping [0], it takes first mode 
mgr_mode=df['MANAGER_ID'].mode()[0]
dep_mode=df['DEPARTMENT_ID'].mode()[0]

In [28]:
print(mgr_mode)
print(dep_mode)

100.0
50.0

In [29]:
df.fillna({'MANAGER_ID':mgr_mode},inplace=True)
df.fillna({'DEPARTMENT_ID':dep_mode},inplace=True)

In [30]:
df.to_csv('cleaned_employee.csv',index=False)
df.to_excel('cleaned_employee.xlsx',index=False)
df.to_json('cleaned_employee.json',indent=4)

## HR data refresh

In [31]:
hr=pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [32]:
hr.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

### Fill Manager Name

In [33]:
hr.fillna({'ManagerID':39},inplace=True)

In [34]:
hr.isna().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       0
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

### Find Duplicate Records

In [35]:
duplicate_emp=hr[hr.duplicated(subset='EmpID')]
duplicate_emp

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
19,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
20,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
21,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
22,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
23,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [36]:
# emp_id=int(input('Enter employee id: '))
# duplicates=hr[hr['EmpID']==emp_id]
# duplicates
# to check duplicates of specific emp id

### Remove Duplicate Records

In [37]:
hr=hr.drop_duplicates(subset='EmpID')
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
326,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
327,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
328,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
329,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

### Remove unwanted values

In [38]:
# strip(), lstrip() -> left strip , rstrip() -> right strip

In [39]:
hr['Department']=hr['Department'].str.strip()

In [40]:
hr['Department'].unique()

array(['Production', 'IT/IS', 'Software Engineering', 'Admin Offices',
       'Sales', 'Executive Office'], dtype=object)

### Extract specific data type column

In [41]:
# select_dtypes()
object_columns = hr.select_dtypes('object')
# object_columns = hr.select_dtypes(['object','float']) for multiple data types
object_columns=object_columns.drop(columns=['DOB','DateofHire','DateofTermination','LastPerformanceReview_Date'])
# since date/time is date data type in excel but takes as str in csv, it cannot have any white space
object_columns

,Employee_Name,Position,State,Gender,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,TermReason,EmploymentStatus,Department,ManagerName,RecruitmentSource,PerformanceScore
0,"Adinolfi, Wilson K",Production Technician I,MA,M,Single,US Citizen,No,White,N/A-StillEmployed,Active,Production,Michael Albert,LinkedIn,Exceeds
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,M,Married,US Citizen,No,White,career change,Voluntarily Terminated,IT/IS,Simon Roup,Indeed,Fully Meets
2,"Akinkuolie, Sarah",Production Technician II,MA,F,Married,US Citizen,No,White,hours,Voluntarily Terminated,Production,Kissy Sullivan,LinkedIn,Fully Meets
3,"Alagbe,Trina",Production Technician I,MA,F,Married,US Citizen,No,White,N/A-StillEmployed,Active,Production,Elijiah Gray,Indeed,Fully Meets
4,"Anderson, Carol",Production Technician I,MA,F,Divorced,US Citizen,No,White,return to school,Voluntarily Terminated,Production,Webster Butler,Google Search,Fully Meets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",Production Technician II,MA,M,Single,US Citizen,No,White,N/A-StillEmployed,Active,Production,Kissy Sullivan,LinkedIn,Fully Meets
326,"Ybarra, Catherine",Production Technician I,MA,F,Single,US Citizen,No,Asian,Another position,Voluntarily Terminated,Production,Brannon Miller,Google Search,PIP
327,"Zamora, Jennifer",CIO,MA,F,Single,US Citizen,No,White,N/A-StillEmployed,Active,IT/IS,Janet King,Employee Referral,Exceeds
328,"Zhou, Julia",Data Analyst,MA,F,Single,US Citizen,No,White,N/A-StillEmployed,Active,IT/IS,Simon Roup,Employee Referral,Fully Meets
329,"Zima, Colleen",Production Technician I,MA,F,Widowed,US Citizen,No,Asian,N/A-StillEmployed,Active,Production,David Stanley,LinkedIn,Fully Meets

In [42]:
object_columns.columns

Index(['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore'],
      dtype='object')

In [43]:
columns=['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore']
for col in columns:
    print(col)
    print('-'*20)
    unique_values=hr[col].unique()
    print(unique_values)
    print('\n')

Employee_Name
--------------------
['Adinolfi, Wilson  K' 'Ait Sidi, Karthikeyan   ' 'Akinkuolie, Sarah'
 'Alagbe,Trina' 'Anderson, Carol ' 'Anderson, Linda  ' 'Andreola, Colby'
 'Athwal, Sam' 'Bachiochi, Linda' 'Bacong, Alejandro '
 'Baczenski, Rachael  ' 'Barbara, Thomas' 'Barbossa, Hector'
 'Barone, Francesco  A' 'Barton, Nader' 'Bates, Norman' 'Beak, Kimberly  '
 'Beatrice, Courtney ' 'Becker, Renee' 'Becker, Scott' 'Bernstein, Sean'
 'Biden, Lowan  M' 'Billis, Helen' 'Blount, Dianna' 'Bondwell, Betsy'
 'Booth, Frank' 'Boutwell, Bonalyn' 'Bozzi, Charles' 'Brill, Donna'
 'Brown, Mia' 'Buccheri, Joseph  ' 'Bugali, Josephine ' 'Bunbury, Jessica'
 'Burke, Joelle' 'Burkett, Benjamin ' 'Cady, Max ' 'Candie, Calvin'
 'Carabbio, Judith' 'Carey, Michael  ' 'Carr, Claudia  N'
 'Carter, Michelle ' 'Chace, Beatrice ' 'Champaigne, Brian' 'Chan, Lin'
 'Chang, Donovan  E' 'Chigurh, Anton' 'Chivukula, Enola'
 'Cierpiszewski, Caroline  ' 'Clayton, Rick' 'Cloninger, Jennifer'
 'Close, Phil' 'Clukey, Elijian' 'Cockel, James' 'Cole, Spencer'
 'Corleone, Michael' 'Corleone, Vito' 'Cornett, Lisa ' 'Costello, Frank'
 'Crimmings,   Jean' 'Cross, Noah' 'Daneault, Lynn' 'Daniele, Ann  '
 "Darson, Jene'ya " 'Davis, Daniel' 'Dee, Randy' 'DeGweck,  James'
 'Del Bosque, Keyla' 'Delarge, Alex' 'Demita, Carla' 'Desimone, Carl '
 'DeVito, Tommy' 'Dickinson, Geoff ' 'Dietrich, Jenna  ' 'DiNocco, Lily '
 'Dobrin, Denisa  S' 'Dolan, Linda' 'Dougall, Eric' 'Driver, Elle'
 'Dunn, Amy  ' 'Dunne, Amy' 'Eaton, Marianne' 'Engdahl, Jean'
 'England, Rex' 'Erilus, Angela' 'Estremera, Miguel' 'Evensen, April'
 'Exantus, Susan' 'Faller, Megan ' 'Fancett, Nicole' 'Ferguson, Susan'
 'Fernandes, Nilson  ' 'Fett, Boba' 'Fidelia,  Libby'
 'Fitzpatrick, Michael  J' 'Foreman, Tanya' 'Forrest, Alex' 'Foss, Jason'
 'Foster-Baker, Amy' 'Fraval, Maruk ' 'Galia, Lisa' 'Garcia, Raul'
 'Gaul, Barbara' 'Gentry, Mildred' 'Gerke, Melisa' 'Gill, Whitney  '
 'Gilles, Alex' 'Girifalco, Evelyn' 'Givens, Myriam' 'Goble, Taisha'
 'Goeth, Amon' 'Gold, Shenice  ' 'Gonzalez, Cayo' 'Gonzalez, Juan'
 'Gonzalez, Maria' 'Good, Susan' 'Gordon, David' 'Gosciminski, Phylicia  '
 'Goyal, Roxana' 'Gray, Elijiah  ' 'Gross, Paula' 'Gruber, Hans'
 'Guilianno, Mike' 'Handschiegl, Joanne' 'Hankard, Earnest'
 'Harrington, Christie ' 'Harrison, Kara' 'Heitzman, Anthony'
 'Hendrickson, Trina' 'Hitchcock, Alfred' 'Homberger, Adrienne  J'
 'Horton, Jayne' 'Houlihan, Debra' 'Howard, Estelle' 'Hudson, Jane'
 'Hunts, Julissa' 'Hutter, Rosalie' 'Huynh, Ming' 'Immediato, Walter'
 'Ivey, Rose ' 'Jackson, Maryellen' 'Jacobi, Hannah  ' 'Jeannite, Tayana'
 'Jhaveri, Sneha  ' 'Johnson, George' 'Johnson, Noelle ' 'Johnston, Yen'
 'Jung, Judy  ' 'Kampew, Donysha' 'Keatts, Kramer '
 'Khemmich, Bartholemew' 'King, Janet' 'Kinsella, Kathleen  '
 'Kirill, Alexandra  ' 'Knapp, Bradley  J' 'Kretschmer, John'
 'Kreuger, Freddy' 'Lajiri,  Jyoti' 'Landa, Hans' 'Langford, Lindsey'
 'Langton, Enrico' 'LaRotonda, William  ' 'Latif, Mohammed' 'Le, Binh'
 'Leach, Dallas' 'LeBlanc, Brandon  R' 'Lecter, Hannibal'
 'Leruth, Giovanni' 'Liebig, Ketsia' 'Linares, Marilyn ' 'Linden, Mathew'
 'Lindsay, Leonara ' 'Lundy, Susan' 'Lunquist, Lisa' 'Lydon, Allison'
 'Lynch, Lindsay' 'MacLennan, Samuel' 'Mahoney, Lauren  '
 'Manchester, Robyn' 'Mancuso, Karen' 'Mangal, Debbie' 'Martin, Sandra'
 'Maurice, Shana' "Carthy, B'rigit" 'Mckenna, Sandy' 'McKinzie, Jac'
 'Meads, Elizabeth' 'Medeiros, Jennifer' 'Miller, Brannon' 'Miller, Ned'
 'Monkfish, Erasumus' 'Monroe, Peter' 'Monterro, Luisa' 'Moran, Patrick'
 'Morway, Tanya' 'Motlagh,  Dawn' 'Moumanil, Maliki ' 'Myers, Michael'
 'Navathe, Kurt' 'Ndzi, Colombui' 'Ndzi, Horia' 'Newman, Richard '
 'Ngodup, Shari ' 'Nguyen, Dheepa' 'Nguyen, Lei-Ming' 'Nowlan, Kristie'
 "O'hare, Lynn" 'Oliver, Brooke ' 'Onque, Jasmine' 'Osturnka, Adeel'
 'Owad, Clinton' 'Ozark, Travis' 'Panjwani, Nina' 'Patronick, Lucas'
 'Pearson, Randall' 'Smith, Martin' 'Pelletier, Ermine' 'Perry, Shakira'
 'Peters, Lauren' 'Peterson, Ebonee  ' 'Petingill, Shana  '
 'Petrowsky, Thelma' 'Pham, Hong' 'Pitt, Brad ' 'Potts, Xana'
 'Power, Morissa' 'Punjabhi, Louis  ' 'Purinton, Janine' 'Quinn, Sean'
 'Rachael, Maggie' 'Rarrick, Quinn' 'Ren, Kylo' 'Rhoads, Thomas'
 'Rivera, Haley  ' 'Roberson, May' 'Robertson, Peter' 'Robinson, Alain  '
 'Robinson, Cherly' 'Robinson, Elias' 'Roby, Lori ' 'Roehrich, Bianca'
 'Roper, Katie' 'Rose, Ashley  ' 'Rossetti, Bruno' 'Roup,Simon'
 'Ruiz, Ricardo' 'Saada, Adell' 'Saar-Beckles, Melinda' 'Sadki, Nore  '
 'Sahoo, Adil' 'Salter, Jason' 'Sander, Kamrin' 'Sewkumar, Nori'
 'Shepard, Anita ' 'Shields, Seffi' 'Simard, Kramer' 'Singh, Nan '
 'Sloan, Constance' 'Smith, Joe' 'Smith, John' 'Smith, Leigh Ann'
 'Smith, Sade' 'Soto, Julia ' 'Soze, Keyser' 'Sparks, Taylor  '
 'Spirea, Kelley' 'Squatrito, Kristen' 'Stanford,Barbara  M'
 'Stansfield, Norman' 'Steans, Tyrone  ' 'Stoica, Rick' 'Strong, Caitrin'
 'Sullivan, Kissy ' 'Sullivan, Timothy' 'Sutwell, Barbara' 'Szabo, Andrew'
 'Tannen, Biff' 'Tavares, Desiree  ' 'Tejeda, Lenora ' 'Terry, Sharlene '
 'Theamstern, Sophia' 'Thibaud, Kenneth' 'Tippett, Jeanette'
 'Torrence, Jack' 'Trang, Mei' 'Tredinnick, Neville ' 'True, Edward'
 'Trzeciak, Cybil' 'Turpin, Jumil' 'Valentin,Jackie' 'Veera, Abdellah '
 'Vega, Vincent' 'Villanueva, Noah' 'Voldemort, Lord' 'Volk, Colleen'
 'Von Massenbach, Anna' 'Walker, Roger' 'Wallace, Courtney  E'
 'Wallace, Theresa' 'Wang, Charlie' 'Warfield, Sarah' 'Whittier, Scott'
 'Wilber, Barry' 'Wilkes, Annie' 'Williams, Jacquelyn  '
 'Winthrop, Jordan  ' 'Wolk, Hang  T' 'Woodson, Jason'
 'Ybarra, Catherine ' 'Zamora, Jennifer' 'Zhou, Julia' 'Zima, Colleen']


Position
--------------------
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'Data Analyst ' 'CIO']


State
--------------------
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']


Gender
--------------------
['M ' 'F']


MaritalDesc
--------------------
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']


CitizenDesc
--------------------
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']


HispanicLatino
--------------------
['No' 'Yes' 'no' 'yes']


RaceDesc
--------------------
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']


TermReason
--------------------
['N/A-StillEmployed' 'career change' 'hours' 'return to school'
 'Another position' 'unhappy' 'attendance' 'performance'
 'Learned that he is a gangster' 'retiring' 'relocation out of area'
 'more money' 'military' 'no-call, no-show' 'Fatal attraction'
 'maternity leave - did not return' 'medical issues' 'gross misconduct']


EmploymentStatus
--------------------
['Active' 'Voluntarily Terminated' 'Terminated for Cause']


Department
--------------------
['Production' 'IT/IS' 'Software Engineering' 'Admin Offices' 'Sales'
 'Executive Office']


ManagerName
--------------------
['Michael Albert' 'Simon Roup' 'Kissy Sullivan' 'Elijiah Gray'
 'Webster Butler' 'Amy Dunn' 'Alex Sweetwater' 'Ketsia Liebig'
 'Brannon Miller' 'Peter Monroe' 'David Stanley' 'Kelley Spirea'
 'Brandon R. LeBlanc' 'Janet King' 'John Smith' 'Jennifer Zamora'
 'Lynn Daneault' 'Eric Dougall' 'Debra Houlihan' 'Brian Champaigne'
 'Board of Directors']


RecruitmentSource
--------------------
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']


PerformanceScore
--------------------
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']

In [44]:
def removeWhiteSpace(dataframe, columns):
    for col in columns:
        dataframe[col]=dataframe[col].str.strip()
    print('Whitespace removed')

In [45]:
removeWhiteSpace(hr,columns)

Whitespace removed

# Replace

In [ ]:
'''
Removing unwanted texts, regular expression (regex)
syntax
--------------------------
for text/characters/digits
    - str.replace(find, replace_value)
for special characters
    - str.replace(find, replace_value, regex=False (True by default))
'''

In [46]:
hr['HispanicLatino'].unique()

array(['No', 'Yes', 'no', 'yes'], dtype=object)

In [47]:
hr['HispanicLatino']=hr['HispanicLatino'].str.replace('yes','Yes')
hr['HispanicLatino'].unique()

array(['No', 'Yes', 'no'], dtype=object)

In [48]:
hr['HispanicLatino']=hr['HispanicLatino'].str.capitalize()
hr['HispanicLatino'].unique()

array(['No', 'Yes'], dtype=object)

In [49]:
hr['Employee_Name']=hr['Employee_Name'].str.replace(',','',regex=False)

In [50]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 0 to 329
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 89.9+ KB

# Datatype Conversion

In [51]:
# astype(datatype)
hr['ManagerID']=hr['ManagerID'].astype(int)

In [ ]:
'''
datetime
----------------------------
- pandas function -> pd.to_datetime(column, format)
- After conversion -> YYYY-MM-DD

format
---------------------------
- %d-%m-%y
- %d.%m.%y
- mixed

dayfirst= True/ False(default)
'''

In [52]:
date_columns=['DOB','DateofHire','DateofTermination','LastPerformanceReview_Date']

In [53]:
hr['DOB']=pd.to_datetime(hr['DOB'])

## Function to convert datetime

In [54]:
def dateconverter(dataframe, *args):
    for col in args:
        hr[col]=pd.to_datetime(hr[col], format ='mixed')
    print('Datetime converted')

In [55]:
dateconverter(hr,'DOB','DateofHire','DateofTermination','LastPerformanceReview_Date')

Datetime converted

In [56]:
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2

In [57]:
hr.to_csv('cleaned_hr.csv',index=False)
hr.to_excel('cleaned_hr.xlsx',index=False)