In [30]:
import pandas as pd

In [31]:
df=pd.read_csv('cleaned_hr.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_month_name,Hire_day_name,Absence_label,Absence_id,Absence_label_id,Col1,Col2,First Name,Middle Name,Last Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absences,0,0,Low,Absences,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absences,2,2,High,Absences,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absences,0,0,Low,Absences,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absences,2,2,High,Absences,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absences,0,0,Low,Absences,Carol,NaN,Anderson

In [32]:
def dateconverter(dataframe, *args):
    for col in args:
        dataframe[col]=pd.to_datetime(dataframe[col], format ='mixed')
    print('Datetime converted')

In [33]:
dateconverter(df,'DOB','DateofHire','DateofTermination','LastPerformanceReview_Date')

Datetime converted

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    datetime64[ns]
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    datetime64[ns]
 22  DateofTermination           104 non-null    datetime64[ns]
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    int64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    datetime64[ns]
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
 36  Hire_year                   311 non-null    int64
 37  Hire_month                  311 non-null    int64
 38  Hire_day                    311 non-null    int64
 39  Hire_month_name             311 non-null    object
 40  Hire_day_name               311 non-null    object
 41  Absence_label               311 non-null    object
 42  Absence_id                  311 non-null    int64
 43  Absence_label_id            311 non-null    int64
 44  Col1                        311 non-null    object
 45  Col2                        311 non-null    object
 46  First Name                  311 non-null    object
 47  Middle Name                 14 non-null     object
 48  Last Name                   311 non-null    object
dtypes: datetime64[ns](4), float64(1), int64(22), object(22)
memory usage: 119.2+ KB

## Extract Year, Month, Day

In [35]:
# df['DateofHire']
'''
Date Number
----------------------
dt.year -> year
dt.month -> month
df.dat -> day

Date Name
----------------------
dt.day_name() -> Day Name
dt.month_name() -> Month Name
'''

'\nDate Number\n----------------------\ndt.year -> year\ndt.month -> month\ndf.dat -> day\n\nDate Name\n----------------------\ndt.day_name() -> Day Name\ndt.month_name() -> Month Name\n'

In [36]:
df['Hire_year']=df['DateofHire'].dt.year
df['Hire_month']=df['DateofHire'].dt.month
df['Hire_day']=df['DateofHire'].dt.day

In [37]:
df['Hire_month_name']=df['DateofHire'].dt.month_name()
df['Hire_day_name']=df['DateofHire'].dt.day_name()

In [38]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_month_name,Hire_day_name,Absence_label,Absence_id,Absence_label_id,Col1,Col2,First Name,Middle Name,Last Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absences,0,0,Low,Absences,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absences,2,2,High,Absences,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absences,0,0,Low,Absences,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absences,2,2,High,Absences,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absences,0,0,Low,Absences,Carol,NaN,Anderson

## Convert Continuous Date into Categorical Data

In [39]:
'''
0 - 5 -> Low Absences
6 - 10 -> Medium Absences
10 - high -> High Absences
'''

'\n0 - 5 -> Low Absences\n6 - 10 -> Medium Absences\n10 - high -> High Absences\n'

In [40]:
df['Absences'].unique()

array([ 1, 17,  3, 15,  2, 19,  4, 16, 12,  9,  7, 20,  8, 13,  5, 14,  6,
       11, 10, 18], dtype=int64)

In [41]:
def absenceCategory(absence):
    if absence >=0 and absence<=5:
        return 'Low Absences'
    elif absence >5 and absence<=10:
        return 'Medium Absences'
    else:
        return 'High Absences'

In [42]:
df['Absence_label']=df['Absences'].apply(absenceCategory) # parameter.apply(function)

In [43]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_month_name,Hire_day_name,Absence_label,Absence_id,Absence_label_id,Col1,Col2,First Name,Middle Name,Last Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absences,0,0,Low,Absences,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absences,2,2,High,Absences,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absences,0,0,Low,Absences,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absences,2,2,High,Absences,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absences,0,0,Low,Absences,Carol,NaN,Anderson

## Date Encoding

### Manual Encoding

In [44]:
# Manual encoding is done for the data that can be compared
# high - medium - low
# (2,1,0)

In [45]:
data ={
    'Low Absences':0,
    'Medium Absences': 1,
    'High Absences': 2
}

In [46]:
df['Absence_id']= df['Absence_label'].map(data)

In [47]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_month_name,Hire_day_name,Absence_label,Absence_id,Absence_label_id,Col1,Col2,First Name,Middle Name,Last Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absences,0,0,Low,Absences,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absences,2,2,High,Absences,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absences,0,0,Low,Absences,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absences,2,2,High,Absences,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absences,0,0,Low,Absences,Carol,NaN,Anderson

In [48]:
def encodedata(dataframe, col_name, *args):
    encode_data={}
    for idx, val in enumerate(args):
        encode_data[val]=idx
    dataframe[f'{col_name}_id']=dataframe[col_name].map(encode_data)
    print(f'{col_name} data encoded.')

In [49]:
encodedata(df,'Absence_label','Low Absences','Medium Absences', 'High Absences')

Absence_label data encoded.

## Split

In [50]:
df['Absence_label'].unique()
# split (find, number_of_columns=index, expand=True/False(default))

array(['Low Absences', 'High Absences', 'Medium Absences'], dtype=object)

In [51]:
df[['Col1','Col2']]=df['Absence_label'].str.split(' ',n=1,expand=True)

In [52]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_month_name,Hire_day_name,Absence_label,Absence_id,Absence_label_id,Col1,Col2,First Name,Middle Name,Last Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absences,0,0,Low,Absences,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absences,2,2,High,Absences,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absences,0,0,Low,Absences,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absences,2,2,High,Absences,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absences,0,0,Low,Absences,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absences,2,2,High,Absences,Jumil,NaN,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absences,0,0,Low,Absences,Jackie,NaN,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absences,2,2,High,Absences,Abdellah,NaN,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absences,2,2,High,Absences,Vincent,NaN,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absences,0,0,Low,Absences,Noah,NaN,Villanueva

In [53]:
hr=pd.read_csv('Dataset/HR_Dataset Refresh.csv')

In [54]:
first_last = hr['Employee_Name'].str.split(',',n=1,expand=True)

In [55]:
first_middle = first_last[1].str.strip().str.split(" ",n=1,expand=True)

In [56]:
df['First Name']=first_middle[0]
df['Middle Name']=first_middle[1]
df['Last Name']=first_last[0]

In [57]:
df.head(22)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_month_name,Hire_day_name,Absence_label,Absence_id,Absence_label_id,Col1,Col2,First Name,Middle Name,Last Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absences,0,0,Low,Absences,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absences,2,2,High,Absences,Karthikeyan,None,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absences,0,0,Low,Absences,Sarah,None,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absences,2,2,High,Absences,Trina,None,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absences,0,0,Low,Absences,Carol,None,Anderson
5,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,January,Monday,High Absences,2,2,High,Absences,Linda,None,Anderson
6,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,November,Monday,High Absences,2,2,High,Absences,Colby,None,Andreola
7,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,September,Monday,High Absences,2,2,High,Absences,Sam,None,Athwal
8,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,July,Monday,Low Absences,0,0,Low,Absences,Linda,None,Bachiochi
9,Bacong Alejandro,10250,0,2,1,1,3,3,0,50178,...,January,Monday,High Absences,2,2,High,Absences,Alejandro,None,Bacong
10,Baczenski Rachael,10252,1,1,0,5,5,3,1,54670,...,January,Monday,High Absences,2,2,High,Absences,Rachael,None,Baczenski
11,Barbara Thomas,10242,1,1,1,5,5,3,1,47211,...,April,Monday,High Absences,2,2,High,Absences,Thomas,None,Barbara
12,Barbossa Hector,10012,0,2,1,1,3,4,1,92328,...,November,Monday,Medium Absences,1,1,Medium,Absences,Hector,None,Barbossa
13,Barone Francesco A,10265,0,0,1,1,5,3,0,58709,...,February,Monday,Medium Absences,1,1,Medium,Absences,Francesco,A,Barone
14,Barton Nader,10066,0,2,1,5,5,3,0,52505,...,September,Monday,Low Absences,0,0,Low,Absences,Nader,None,Barton
15,Bates Norman,10061,0,0,1,4,5,3,0,57834,...,February,Monday,High Absences,2,2,High,Absences,Norman,None,Bates
16,Beak Kimberly,10023,1,1,0,2,5,4,0,70131,...,July,Thursday,High Absences,2,2,High,Absences,Kimberly,None,Beak
17,Beatrice Courtney,10055,0,0,0,1,5,3,0,59026,...,April,Monday,High Absences,2,2,High,Absences,Courtney,None,Beatrice
18,Becker Renee,10245,0,0,0,4,3,3,0,110000,...,July,Monday,Medium Absences,1,1,Medium,Absences,Renee,None,Becker
19,Becker Scott,10277,0,0,1,3,5,3,0,53250,...,July,Monday,High Absences,2,2,High,Absences,Wilson,K,Adinolfi
20,Bernstein Sean,10046,0,0,1,1,5,3,0,51044,...,April,Monday,High Absences,2,2,High,Absences,Karthikeyan,None,Ait Sidi
21,Biden Lowan M,10226,0,2,0,1,5,3,0,64919,...,August,Monday,Low Absences,0,0,Low,Absences,Sarah,None,Akinkuolie

In [ ]:
df.to_csv('cleaned_hr.csv',index=False)