In [2]:
import pandas as pd

In [3]:
'''
- File handling
- Data Wrangling
    - Data cleaning
    - Data transformation
    - Data analysis
    - Feature engineering
'''

'\n- File handling\n- Data Wrangling\n    - Data cleaning\n    - Data transformation\n    - Data analysis\n    - Feature engineering\n'

In [4]:
# 1D -> Series -> pd.Series( 1d list)
# 2D -> DataFrame -> pd.DataFrame(2D list)

# Pandas shows both index and values of the data.

In [5]:
numbers = pd.Series([1,2,3,4,5])
numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data =[1,2,3,4,5]
for idx,val in enumerate(data):
    print(f'{idx}  {val}')
print(f'dtype: {type(val)}')

0  1
1  2
2  3
3  4
4  5
dtype: <class 'int'>

In [7]:
products=pd.DataFrame([
    ['Mobile','Samsung','Rs.60000'],
    ['Laptop','acer','Rs.100000'],
    ['TV','Samsung','Rs.120000'],
    ['Charger','Readme','Rs.1000']
],columns=['Products Name','Brand','Price'],
    index=['A','B','C','D']) # we usually don't give names for row index
products

  Products Name    Brand      Price
A        Mobile  Samsung   Rs.60000
B        Laptop     acer  Rs.100000
C            TV  Samsung  Rs.120000
D       Charger   Readme    Rs.1000

In [8]:
numbers.shape

(5,)

In [9]:
products.shape

(4, 3)

In [10]:
products.size # total no. of data

12

In [11]:
# nth dimension
products.ndim

2

In [12]:
# indexing is same for 1D for list, numpy and pandas
# for multi-d it's same as numpy if we have to extract certain rows and columns

# Loc and ILOC

In [13]:
# - loc -> extract data using alphabetical index
# - iloc -> extract data using integer index

In [14]:
products.iloc[1:4,1:]

     Brand      Price
B     acer  Rs.100000
C  Samsung  Rs.120000
D   Readme    Rs.1000

In [15]:
products.loc['B':'D','Brand':]

     Brand      Price
B     acer  Rs.100000
C  Samsung  Rs.120000
D   Readme    Rs.1000

In [16]:
products.iloc[
    [0,1,3],
    [0,2]
]

  Products Name      Price
A        Mobile   Rs.60000
B        Laptop  Rs.100000
D       Charger    Rs.1000

# Functions for File Handling

## Read Files

In [17]:
'''
CSV File -> read_csv(file_name.csv)
Excel File -> read_excel(file_name.xlsx)
JSON File -> read_json(file_name.josn)
SQL File -> read_sql(file_name.sql)
'''

'\nCSV File -> read_csv(file_name.csv)\nExcel File -> read_excel(file_name.xlsx)\nJSON File -> read_json(file_name.josn)\nSQL File -> read_sql(file_name.sql)\n'

## Create File

In [18]:
'''
CSV File -> to_csv(file_name.csv, index=False)
Excel File -> to_excel(file_name.xlsx, index= False)
JSON File -> to_json(file_name.json, indent=4)
'''

'\nCSV File -> to_csv(file_name.csv, index=False)\nExcel File -> to_excel(file_name.xlsx, index= False)\nJSON File -> to_json(file_name.json, indent=4)\n'

In [19]:
# Read file
df=pd.read_csv('Dataset/Cardiovascular_Disease.csv')
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [20]:
df.head() # gives top 5 records by default/ without argument

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [21]:
df.tail() # gives bottom 5 records

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [22]:
df.head(10) # we can adjust the number of records to be shown by argument

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
5,8,21914,1,151,67.0,120,80,2,2,0,0,0,0
6,9,22113,1,157,93.0,130,80,3,1,0,0,1,0
7,12,22584,2,178,95.0,130,90,3,3,0,0,1,1
8,13,17668,1,158,71.0,110,70,1,1,0,0,1,0
9,14,19834,1,164,68.0,110,60,1,1,0,0,0,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [24]:
emp=pd.read_csv("Dataset/Employees.csv")
emp.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [25]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [26]:
'''
NaN -> Not a Number -> Numeric/ Alphabetical
NaT -> Not a Time -> Date/Time
'''

'\nNaN -> Not a Number -> Numeric/ Alphabetical\nNaT -> Not a Time -> Date/Time\n'

In [27]:
df=pd.read_csv('Dataset/Cardiovascular_Disease.csv')
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [28]:
df=pd.read_csv('Dataset/Employees.csv')

In [29]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

# Conditional Filtering

In [30]:
df=pd.read_csv('Dataset/Car_Sales.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [31]:
df[df['year']==2017][['name','year','selling_price']]

                                 name  year  selling_price
3              Datsun RediGO T Option  2017         250000
9            Maruti Celerio Green VXI  2017         365000
16             Datsun RediGO T Option  2017         250000
22           Maruti Celerio Green VXI  2017         365000
54    Maruti Swift Dzire VDI Optional  2017         725000
...                               ...   ...            ...
4264           Hyundai i20 1.4 Sportz  2017         680000
4273           Maruti Ertiga SHVS VDI  2017         890000
4309                 Datsun GO Plus T  2017         350000
4311          Toyota Camry Hybrid 2.5  2017        1900000
4315               Maruti Celerio ZXI  2017         415000

[466 rows x 3 columns]

In [32]:
df.loc[(df['selling_price']>=300000) & (df['selling_price']<=600000), ['name','year','selling_price']]

                                              name  year  selling_price
2                             Hyundai Verna 1.6 SX  2012         600000
4                            Honda Amaze VX i-DTEC  2014         450000
6                        Hyundai Xcent 1.2 Kappa S  2016         550000
9                         Maruti Celerio Green VXI  2017         365000
15                            Hyundai Verna 1.6 SX  2012         600000
...                                            ...   ...            ...
4322                 Hyundai Verna 1.6 SX CRDi (O)  2013         500000
4331          Ford EcoSport 1.5 TDCi Titanium BSIV  2015         530000
4334  Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV  2012         600000
4335           Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999
4336                    Hyundai i20 Magna 1.4 CRDi  2014         409999

[1560 rows x 3 columns]

In [33]:
df[(df['selling_price']>=300000)&(df['selling_price']<=600000)]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4322,Hyundai Verna 1.6 SX CRDi (O),2013,500000,120000,Diesel,Individual,Manual,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [34]:
df[(df['selling_price']>=300000)&(df['selling_price']<=600000)][['name','year','selling_price']]

                                              name  year  selling_price
2                             Hyundai Verna 1.6 SX  2012         600000
4                            Honda Amaze VX i-DTEC  2014         450000
6                        Hyundai Xcent 1.2 Kappa S  2016         550000
9                         Maruti Celerio Green VXI  2017         365000
15                            Hyundai Verna 1.6 SX  2012         600000
...                                            ...   ...            ...
4322                 Hyundai Verna 1.6 SX CRDi (O)  2013         500000
4331          Ford EcoSport 1.5 TDCi Titanium BSIV  2015         530000
4334  Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV  2012         600000
4335           Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999
4336                    Hyundai i20 Magna 1.4 CRDi  2014         409999

[1560 rows x 3 columns]

In [35]:
df[df['selling_price'].between(300000,600000)]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4322,Hyundai Verna 1.6 SX CRDi (O),2013,500000,120000,Diesel,Individual,Manual,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [36]:
df[df['selling_price'].between(300000,600000)][['name','year','selling_price']]

                                              name  year  selling_price
2                             Hyundai Verna 1.6 SX  2012         600000
4                            Honda Amaze VX i-DTEC  2014         450000
6                        Hyundai Xcent 1.2 Kappa S  2016         550000
9                         Maruti Celerio Green VXI  2017         365000
15                            Hyundai Verna 1.6 SX  2012         600000
...                                            ...   ...            ...
4322                 Hyundai Verna 1.6 SX CRDi (O)  2013         500000
4331          Ford EcoSport 1.5 TDCi Titanium BSIV  2015         530000
4334  Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV  2012         600000
4335           Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999
4336                    Hyundai i20 Magna 1.4 CRDi  2014         409999

[1560 rows x 3 columns]

In [37]:
# to find unique values
df['fuel'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [38]:
# to find number of unique values in a column
df['fuel'].nunique()

5

In [39]:
# find cars whose emmision type is petrol or CNG
car_fuel=df[(df['fuel']=='Petrol') | (df['fuel']=='CNG')]
car_fuel

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [40]:
car_fuel_in=df[df['fuel'].isin(['Petrol','CNG'])]

In [41]:
car_fuel_in

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [42]:
''' find car types whose transmission mode is Automatic, fuel type is Petrol/Electric and 
which is driven around 20000 to 35000 range
'''

' find car types whose transmission mode is Automatic, fuel type is Petrol/Electric and \nwhich is driven around 20000 to 35000 range\n'

In [43]:
car_types=df[(df['transmission']=='Automatic') & 
             ((df['fuel']=='Petrol') | (df['fuel']=='Diesel')) &
             # (df['km_driven'].between(20000,35000))]
             ((df['km_driven']>=20000) & (df['km_driven']<=35000))]
car_types

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
12,Toyota Corolla Altis 1.8 VL CVT,2018,1650000,25000,Petrol,Dealer,Automatic,First Owner
25,Toyota Corolla Altis 1.8 VL CVT,2018,1650000,25000,Petrol,Dealer,Automatic,First Owner
29,Jaguar XF 2.2 Litre Luxury,2014,1964999,28000,Diesel,Dealer,Automatic,First Owner
36,Mercedes-Benz New C-Class C 220 CDI Avantgarde,2012,1375000,33800,Diesel,Dealer,Automatic,Second Owner
94,Audi A6 2.0 TDI Premium Plus,2014,1470000,34000,Diesel,Dealer,Automatic,Second Owner
...,...,...,...,...,...,...,...,...
4254,Hyundai Verna CRDi 1.6 AT EX,2018,1100000,25000,Diesel,Individual,Automatic,Second Owner
4274,Hyundai Verna CRDi 1.6 AT EX,2018,1100000,25000,Diesel,Individual,Automatic,Second Owner
4302,BMW 7 Series 730Ld,2006,1050000,30000,Diesel,Dealer,Automatic,First Owner
4304,Audi Q5 3.0 TDI Quattro Technology,2018,3899000,22000,Diesel,Dealer,Automatic,First Owner
4311,Toyota Camry Hybrid 2.5,2017,1900000,20118,Petrol,Dealer,Automatic,First Owner

In [44]:
'''
Data types
-----------
-int , str, bool, None, complex, float, datetime

Types of data
---------------
-Numeric:
   -Discrete
   -Continuous

-Categorical
   -nominal -> category which cannot be compared
   -ordinal -> category which can be compared
'''

'\nData types\n-----------\n-int , str, bool, None, complex, float, datetime\n\nTypes of data\n---------------\n-Numeric:\n   -Discrete\n   -Continuous\n\n-Categorical\n   -nominal -> category which cannot be compared\n   -ordinal -> category which can be compared\n'

In [45]:
temp=df[(df['selling_price']>=300000) & (df['selling_price']<=600000)][['name','year','selling_price']]
temp

                                              name  year  selling_price
2                             Hyundai Verna 1.6 SX  2012         600000
4                            Honda Amaze VX i-DTEC  2014         450000
6                        Hyundai Xcent 1.2 Kappa S  2016         550000
9                         Maruti Celerio Green VXI  2017         365000
15                            Hyundai Verna 1.6 SX  2012         600000
...                                            ...   ...            ...
4322                 Hyundai Verna 1.6 SX CRDi (O)  2013         500000
4331          Ford EcoSport 1.5 TDCi Titanium BSIV  2015         530000
4334  Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV  2012         600000
4335           Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999
4336                    Hyundai i20 Magna 1.4 CRDi  2014         409999

[1560 rows x 3 columns]

In [46]:
temp = df[df['selling_price'].apply(lambda x: (x>=300000 & x<=600000))]
temp

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner